### ISSUE TITLE
author search not selective enough

### ISSUE THREAD

**Issue by romanchyla** [adsabs/montysolr#107]
this query ```(author:"van der Wiel, M.H.D" OR author:"van der Wiel, Matthijs" year:2008-2018) AND author:"van der Wiel, Marleen"```

translated into: ```"+(+(author:van der wiel, m h d author:van der wiel, m h d* author:/van der wiel, m[^ ]+/ author:/van der wiel, m[^ ]+ h[^ ]+/ author:/van der wiel, m[^ ]+ h[^ ]+ d.*/ author:van der wiel, m[^ ]+ h[^ ]+ * author:van der wiel, m[^ ]+ h[^ ]+ d.* * author:van der wiel, m author:van der wiel, author:van der wiel, matthijs author:van der wiel, matthijs * author:van der wiel, m author:van der wiel, m * author:van der wiel,) +year:[2008 TO 2018]) +(author:van der wiel, marleen author:van der wiel, marleen * author:van der wiel, m author:van der wiel, m * author:van der wiel,)"```

which, amongst others, matches:

```
{
        "bibcode":"2016PLoSO..1158277S",
        "author":["Sakes, Aimée",
          "van der Wiel, Marleen",
          "Henselmans, Paul W. J.",
          "van Leeuwen, Johan L.",
          "Dodou, Dimitra",
          "Breedveld, Paul"]},
{
        "bibcode":"2010A&A...521L..43V",
        "author":["van der Wiel, M. H. D.",
          "van der Tak, F. F. S.",
          "Lis, D. C.",
          "Bell, T.",
          "Bergin, E. A.",
          "Comito, C.",
          "Emprechtinger, M.",
          "Schilke, P.",
          "Caux, E.",
```

the problematic condition here is the `author:van der wiel, m *` which allows to match `van der Wiel, M. H. D.`

we are favoring recall at the expense of precision; it was a sticky point in the past  (to be revisited?)

**Comment by aaccomazzi** [comment]
The author expansion follows our stated attempt at matching all author signatures that are compatible with the search string.  It sounds to me that this is a case where we should require an exact author match?

**Comment by romanchyla** [comment]
I think I understand your position - the author signature could be 'incomplete' and therefore the `author:van der wiel, m *` is our best effort to include whatever author has a signature that starts with `m` (effectively saying - the users cannot know all the names they should be trying to include; while I tend to think that users know and if they told me to search for one name, they know it should be only one first name)

by `require an exact author match` you mean in BBB?

**Comment by JCRPaquin** [comment]
This is intended behavior; if the user wants to limit searches to the particular author they should use an exact search for that author.
