### ISSUE TITLE
Support for editor, book_author and series

### ISSUE THREAD

**Issue by spacemansteve** [adsabs/montysolr#111]
Expand schema to support the 3 new fields: editor, book_author and series.  These fields have been added to [our probobufs](https://github.com/adsabs/ADSPipelineMsg/pull/50).
```
repeated string book_author = 96;
repeated string editor = 97;
string series = 98;
```
Steve will generate a PR for Roman to review.  It will include changes to [schema.xml](https://github.com/romanchyla/montysolr/blob/master/contrib/examples/adsabs/server/solr/collection1/conf/schema.xml) and [TestAdsAllFields.java](https://github.com/romanchyla/montysolr/blob/master/contrib/adsabs/src/test/org/adsabs/TestAdsAllFields.java).

**Comment by spacemansteve** [comment]
The [book_author field](https://github.com/romanchyla/montysolr/blob/master/contrib/examples/adsabs/server/solr/collection1/conf/schema.xml#L1185) and the [editor field](https://github.com/romanchyla/montysolr/blob/master/contrib/examples/adsabs/server/solr/collection1/conf/schema.xml#L1188) is already in the schema.  Only series needs to be added.

**Comment by spacemansteve** [comment]
What if the value of the series is not ascii?  Do characters get downgraded?

**Comment by romanchyla** [comment]
Yes, they will downgraded
