### ISSUE TITLE
Index affiliation abbreviations in new "institution" field

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/montysolr#126]
We currently index abbreviations for author affiliations in a two-tiered system, as currently provided in the aff_facet_hier description.  We would like to enable a search to be done using a similar mechanism, i.e.:

```
institution:"Harvard U/CfA"     # searches for both parent and child, most precise search
institution:"Harvard U"         # searches for parent only, broad search
institution:"CfA"               # searches for child name, may not be unique across all entries 
```
In order to enable this, the pipeline will generate the `institution` field following the syntax `Parent/Child`, and SOLR will tokenize it in the following way:

* All text should be normalized and treated like keywords (mapped to ascii, lowercased, no splitting on whitespace)
* No use of synonyms or acronyms
* At indexing time `Parent/Child` generates the tokens: `Parent/Child`, `Parent`, `Child` (all with the same position)
* If no child is present, generate one token, i.e. `Parent` remains `Parent`
* At search time, only normalization occurs, which allows one to find the expected results as described in the above cases.

Note that while the list of institution abbreviations found in the parent field is guaranteed to be unique (as is the combination `Parent/Child`), the same child abbreviation can appear in multiple entries.  This is a feature and will allow a user for instance, to search for `institution:"Phys Dept"` and find all the places which have a physics department.

**Comment by aaccomazzi** [comment]
A quick clarification: this content is currently being created for the `aff_abbrev` field.  Here I'm simply suggesting to change the name of the field and use a proper tokenizer (the current parser for `aff_abbrev` is ads_text which is used for unstructured text content).

**Comment by spacemansteve** [comment]
@romanchyla should the search for [IMCCE](https://github.com/romanchyla/montysolr/blob/master/contrib/adsabs/src/test/org/apache/solr/analysis/TestAdsabsTypeAffiliationText.java#L88) in TestAdsabsTypeAffiliationText.java return 0?

**Comment by romanchyla** [comment]
it should return 1, based on this: https://github.com/romanchyla/montysolr/blob/master/contrib/adsabs/src/test/org/apache/solr/analysis/TestAdsabsTypeAffiliationText.java#L59

but search for 'observatoire' should return 0

that search, however, isn't it against `aff_abbrev`? i have lost track since - is `aff` supposed to be a virtual field?
