### ISSUE TITLE
Unable to search pubnote for a DOI

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/montysolr#193]
A search for `pubnote:"10.1214/088342304000000378"` generates the following error:
```
field \"pubnote\" was indexed without position data; cannot run PhraseQuery (phrase=pubnote:\"10 1214 088342304000000378\")"
```
It looks like we can fix this by updating the schema and have pubnote indexed using the `adstext` field type.

**Comment by aaccomazzi** [comment]
Actually it looks like the change required in the schema is to simply remove `omitTermFreqAndPositions="true"` from this entry:
```
		<field name="pubnote" type="ads_text" indexed="true"
			stored="true" multiValued="true" omitNorms="true"
			omitTermFreqAndPositions="true" />
```
And while we're at it, we should remove it from the `comment` field as well.

https://github.com/adsabs/montysolr/blob/master/contrib/examples/adsabs/server/solr/collection1/conf/schema.xml#L1424

**Comment by JCRPaquin** [comment]
`omitTermFreqAndPositions="true"` was removed from the schema (not sure when), and the query doesn't return an error-- but it also doesn't return any results. I searched the paper by title and it _is_ in the index.

I'll work on setting up a test with this document to see why the `pubnote` query isn't matching it.

**Comment by aaccomazzi** [comment]
The search for the pubnote field works fine, but the example offered earlier is no longer present in our database.
We can use this instead: `pubnote:"10.1016/j.dark.2023.101310"`
