### ISSUE TITLE
Implement last author positional search

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/montysolr#206]
We know it's difficult, but the last author name (and last orcid, etc) position is significant for the life sciences.
Basically we need to implement the ability to say:
```
pos(author:"accomazzi, alberto", -1)
```
This should return all records where the search term has the last position.

All fields supporting positional searches should provide this functionality (e.g. `orcid`, `institution`, etc).

**Comment by aaccomazzi** [comment]
It would of course be nice to generalize this so we can search for a name in the last N positions of an author field:
```
pos(author:"accomazzi, a", -3)
```
and even:
```
pos(author:"accomazzi, a", -5, -1)
```
(which returns records where "accomazzi, a" appears in the last 5 positions).
As syntactic sugar, we could also adopt classic's notation with the `$`:
```
author:"$accomazzi, a"
```
(similar to what we do now with `^` for first author)

**Comment by JCRPaquin** [comment]
Partial implementation in this PR: https://github.com/adsabs/montysolr/pull/212
