### ISSUE TITLE
Missing upstream-include.xml During Build

### ISSUE THREAD

**Issue by sharifzadeh** [adsabs/montysolr#217]
I encountered an issue while trying to build montysolr on my Windows 11 system. When running the ant build-all command, the build process fails with the following error:
Cannot find C:\Users\...\montysolr\upstream-include.xml imported from C:\Users\...\montysolr\montysolr\build.xml

Ant file: 

<project name="adsabs" default="default" xmlns:ivy="antlib:org.apache.ivy.ant">

	<description>
	    ADS search engine extensions
    </description>
    <property name="solr.nature" value="true"/>
	<import file="../upstream-include.xml" />

**Comment by JCRPaquin** [comment]
Hi @sharifzadeh,

We've switched from Ant to Gradle. To build the project, please do `./gradlew build` from the repository root. 

Alternatively, if you're using an IDE that supports Gradle (e.g. IntelliJ) the build script may be automatically detected.

**Comment by JCRPaquin** [comment]
I've also gone ahead and updated the build commands in the root README.md, thanks for calling this out!

**Comment by JCRPaquin** [comment]
Marking this as resolved. If you have further build issues, please open a new issue.
