### ISSUE TITLE
author:(accomazzi,a kurtz,m) returns 0 records

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/montysolr#35]
But the following queries instead work:

```
author:accomazzi,a author:kurtz,m
author:("accomazzi,a" "kurtz,m")
```

Therefore it looks like the parsing rules inside the parenthesis are different, and can't deal with the syntax "last,f" without quotes.  Ideally we'd like to remove the limitation so that people are not forced to put double quotes around author:() tokens

**Comment by romanchyla** [comment]
yes, i have seen people not getting it - but is hard `author:(kurtz, michael john antoine, levry)`
