### ISSUE TITLE
Optimize body:*

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/montysolr#62]
Right now there is no way to find out what documents have fulltext due to the fact that the query times out during the 30 seconds allowed for its execution.  

I often use queries such as this one to spot problems in our coverage but consistently get http 504 responses (timeout).  I suspect the implementation of the wildcard search could use optimization, since interestingly the search "*:*" works fine most of the time.

**Comment by JCRPaquin** [comment]
Should be resolved once we have `has` field
